version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    ports:
      - "5429:5432"